version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: shery
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - C:/Users/rupes/OneDrive/Desktop/DevOps/test:/data/db
    networks:
      - app-network

    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5050"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: shery
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
      ME_CONFIG_MONGODB_URL: mongodb://shery:qwerty@mongo:27017/
    depends_on:
      - mongo

    networks:
      - app-network

networks:
  app-network:
    driver: bridge
